//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace webdogo {
    
    
    public partial class Default {
        
        /// <summary>
        /// ctr_header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::webdogo.ctr.ctr_header ctr_header;
        
        /// <summary>
        /// ctr_silde control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::webdogo.ctr.ctr_silde ctr_silde;
        
        /// <summary>
        /// ctr_content control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::webdogo.ctr.ctr_content ctr_content;
        
        /// <summary>
        /// ctr_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::webdogo.ctr.ctr_right ctr_right;
        
        /// <summary>
        /// ctr_footer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::webdogo.ctr.ctr_footer ctr_footer;
    }
}
